In [1]:
import numpy as np
from keras.datasets import mnist
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

from task01_ashirmatovad_tests import test_knn_model
from task01_ashirmatovad_model import KnnBalltreeClassifier

In [11]:
MyKnn = KnnBalltreeClassifier(n_neighbors = 11, weights = 'distance', leaf_size = 100)
test = test_knn_model(MyKnn)
test.small_test_on_mnist_and_comparing_with_sklearn()
test.test_for_exeptions()



Small test on mnist and comparing with sklearn

train_x_shape (700, 784)
test_x_shape (300, 784)

Builded model: n_neighbors = 11, weights = distance, leaf_size = 100
Fitting model

Creating sklearn with same params, fitting it

Just for check give for predict train_x and accuracy should be 1.0
Accuracy = 1.0, all is ok

Make predict and compare 2 arrays
No error in predict

Make predict_proba and compare 2 matrices, using np.around(..., 5)
No error in predict_proba

Make kneighbors and compare, n_neighbors = 5
No error in kneighbors


Test on exeptions


Builded model: n_neighbors = 11, weights = distance, leaf_size = 100

Try to give as X string for fit:
Wrong type of X

Try predict, without fitting:
Model is not fitted yet

Try predict_proba, without fitting:
Model is not fitted yet

Try kneighbors, without fitting:
Model is not fitted yet

Gen random dataset, X_small will be 2d point, with function np.random.rand. len(X_small) = n_neighbors (in builded model)
X_small.shape (11, 2

 Тест, в котором нужно варировать параметры конструктора, поэтому его не вставил в класс test_knn_model

In [3]:
def small_test():
    print("Test on small input\n")
    X_small = np.array([[1, 0], [0, 10], [20, 0], [100, 0]])
    Y_small = np.array(['A', 'B', 'C', 'D'])
    print("X_small\n", X_small)
    print("Y_small\n", Y_small, "\n")
    print("Building model, n_neighbors = 1, weights = 'uniform'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 1, weights = 'uniform')
    MyKnn.fit(X_small, Y_small)
    QueryMatrix = np.array([[0, 0]])
    print("MyQuery\n", QueryMatrix)
    print("predict")
    print(MyKnn.predict(QueryMatrix = QueryMatrix))
    print("predict_proba")
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    print("kneighbors, n_neighbors = 1")
    print(MyKnn.kneighbors(QueryMatrix = QueryMatrix, n_neighbors = 1))
    print("kneighbors, n_neighbors = 3")
    print(MyKnn.kneighbors(QueryMatrix = QueryMatrix, n_neighbors = 3))

    print("\nNow i will iterate over n_neighbors and weights, check predict_proba, because predict and kneighbors will work the same")

    print("\nBuilding model, n_neighbors = 2, weights = 'uniform'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 2, weights = 'uniform', leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))

    print("\nBuilding model, n_neighbors = 3, weights = 'uniform'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 3, weights = 'uniform', leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))

    print("\nBuilding model, n_neighbors = 4, weights = 'uniform'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 4, weights = 'uniform', leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))

    print("\nBuilding model, n_neighbors = 2, weights = 'distance'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 2, weights = 'distance', leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    # 1 - вес 1-го соседа. 0.1 - вес 2-го соседа, общий вес 1.1
    print("Should be", 1/1.1, 0.1/1.1, 0, 0)

    print("\nBuilding model, n_neighbors = 3, weights = 'distance'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 3, weights = 'distance', leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    # 1 - вес 1-го соседа. 0.1 - вес 2-го соседа, 0.05 - вес 3-го соседа, общий вес = 1.15
    print("Should be", 1/1.15, 0.1/1.15, 0.05/1.15, 0)

    print("\nBuilding model, n_neighbors = 4, weights = 'distance'")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 4, weights = 'distance', leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    # 1 - вес 1-го соседа. 0.1 - вес 2-го соседа, 0.05 - вес 3-го соседа, 0.01 - вес 4-го соседа, общий вес = 1.16
    print("Should be", 1/1.16, 0.1/1.16, 0.05/1.16, 0.01/1.16)

    def my_own_function(dst):
        return 1 / dst**2

    print("\nMy own function is f(d) = 1/d^2")

    print("\nBuilding model, n_neighbors = 2, weights = my_own_function")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 2, weights = my_own_function, leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    # 1 - вес 1-го соседа. 0.01 - вес 2-го соседа, общий вес 1.01
    print("Should be", 1/1.01, 0.01/1.01, 0, 0)

    print("\nBuilding model, n_neighbors = 3, weights = my_own_function")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 3, weights = my_own_function, leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    # 1 - вес 1-го соседа. 0.01 - вес 2-го соседа, 0.0025 - вес 3-го соседа, общий вес 1.0125
    print("Should be", 1/1.0125, 0.01/1.0125, 0.0025/1.0125, 0)

    print("\nBuilding model, n_neighbors = 4, weights = my_own_function")
    MyKnn = KnnBalltreeClassifier(n_neighbors = 4, weights = my_own_function, leaf_size = 1)
    MyKnn.fit(X_small, Y_small)
    print(MyKnn.predict_proba(QueryMatrix = QueryMatrix))
    # 1 - вес 1-го соседа. 0.01 - вес 2-го соседа, 0.0025 - вес 3-го соседа, 0.0001 - вес 4-го соседа, общий вес 1.0126
    print("Should be", 1/1.0126, 0.01/1.0126, 0.0025/1.0126, 0.0001/1.0126)

In [4]:
small_test()

Test on small input

X_small
 [[  1   0]
 [  0  10]
 [ 20   0]
 [100   0]]
Y_small
 ['A' 'B' 'C' 'D'] 

Building model, n_neighbors = 1, weights = 'uniform'
MyQuery
 [[0 0]]
predict
['A']
predict_proba
[[1. 0. 0. 0.]]
kneighbors, n_neighbors = 1
(array([[1.]]), array([[0]]))
kneighbors, n_neighbors = 3
(array([[ 1., 10., 20.]]), array([[0, 1, 2]]))

Now i will iterate over n_neighbors and weights, check predict_proba, because predict and kneighbors will work the same

Building model, n_neighbors = 2, weights = 'uniform'
[[0.5 0.5 0.  0. ]]

Building model, n_neighbors = 3, weights = 'uniform'
[[0.33333333 0.33333333 0.33333333 0.        ]]

Building model, n_neighbors = 4, weights = 'uniform'
[[0.25 0.25 0.25 0.25]]

Building model, n_neighbors = 2, weights = 'distance'
[[0.90909091 0.09090909 0.         0.        ]]
Should be 0.9090909090909091 0.09090909090909091 0 0

Building model, n_neighbors = 3, weights = 'distance'
[[0.86956522 0.08695652 0.04347826 0.        ]]
Should be 0.869

Применяю к прикладной задаче машинного обучения - к датасету mnist. Сначала, взяв не всю базу, я посмотрю, при каких гиперпараметрах работает лучше

In [10]:
from keras.datasets import mnist
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

(train_x, train_y), (test_x, test_y) = mnist.load_data()
train_x = train_x.reshape(len(train_x), 784)
test_x = test_x.reshape(len(test_x), 784)
print(train_x.shape, test_x.shape)
train_x = np.float32(train_x)
test_x = np.float32(test_x)

def my_own_function(dst):
    return 1 / dst**2
    
for weights in ['uniform', 'distance', my_own_function]:
    for k in range(1, 12, 2):
        MyKnn = KnnBalltreeClassifier(n_neighbors = k, weights = weights, leaf_size = 100)
        MyKnn.fit(train_x[:1000], train_y[:1000])
        acc = MyKnn.predict(test_x[:200])
        print(weights, k, accuracy_score(acc, test_y[:200]))

(60000, 784) (10000, 784)
uniform 1 0.85
uniform 3 0.845
uniform 5 0.875
uniform 7 0.855
uniform 9 0.845
uniform 11 0.825
distance 1 0.85
distance 3 0.855
distance 5 0.875
distance 7 0.86
distance 9 0.865
distance 11 0.84
<function my_own_function at 0x7f8919bc33a0> 1 0.85
<function my_own_function at 0x7f8919bc33a0> 3 0.855
<function my_own_function at 0x7f8919bc33a0> 5 0.875
<function my_own_function at 0x7f8919bc33a0> 7 0.86
<function my_own_function at 0x7f8919bc33a0> 9 0.865
<function my_own_function at 0x7f8919bc33a0> 11 0.85


На n_neighbors = 5, weights = 'distance' работает хорошо, буду использовать его. Проверю

In [14]:
MyKnn = KnnBalltreeClassifier(n_neighbors = 5, weights = 'distance', leaf_size = 100)
MyKnn.fit(train_x[:5000], train_y[:5000])
acc = MyKnn.predict(test_x[:1000])
print(accuracy_score(acc, test_y[:1000]))

0.914


Работает хорошо. Теперь возьму в качестве train_x[:10000], и сделаю predict всего test

In [15]:
MyKnn = KnnBalltreeClassifier(n_neighbors = 5, weights = 'distance', leaf_size = 500)
MyKnn.fit(train_x[:10000], train_y[:10000])
acc = MyKnn.predict(test_x)
print(accuracy_score(acc, test_y))

0.9476


Йеху!